from django.conf.urls import url
from forminfo import views
from .views import *

urlpatterns = [
    url(r"^addform-plan/$", views.addinfo_plan),
    url(r"^addinfoplan/$", views.addinfoplan_),
    url(r"^addform-event/$", views.addinfo_event),
    url(r"^addinfoevent/$", views.addinfoevent_),
    url(r"^eventrevise/$", views.revise_event),
    url(r"^planrevise/$", views.revise_plan),
    url(r"^changeplaninfo/$",views.show_plandetail),
    url(r"^changeeventinfo/$",views.show_eventdetail),
    url(r"^planresult/$",views.update_planform),
    url(r"^eventresult/$",views.update_eventform),
    url(r"^plan/$",views.info_plan),
    url(r"^event/$",views.info_event),
    url(r"^work/$",views.info_work),
    url(r"^addinfowork/$",views.addinfowork_),
    url(r"^workrevise/$", views.revise_work),
    url(r"^changeworkinfo/$",views.show_workdetail),
    url(r"^workresult/$",views.update_workform),
    url(r"^addform-work", views.addinfo_work),
    url(r"^amend-plan/$",views.amend_plan),
    url(r"^amend-event/$",views.amend_event),
    url(r"^amend-work/$",views.amend_work),
    url(r"^amendplaninfo/$",views.amendplaninfo_),
    url(r"^amendplaninfoshow/$",views.amendplaninfoshow_),
    url(r"^amendeventinfo/$",views.amendeventinfo_),
    url(r"^amendeventinfoshow/$",views.amendeventinfoshow_),
    url(r"^amendworkinfo/$",views.amendworkinfo_),
    url(r"^amendworkinfoshow/$",views.amendworkinfoshow_),
    url(r"^exportfaeplan/$",views.export_excelplan),
    url(r"^exportfaeevent/$",views.export_excelevent),
    url(r"^exportfaework/$",views.export_excelwork),
    url(r"^excelplan/$",views.excelplan),
    url(r"^excelevent/$",views.excelevent),
    url(r"^excelwork/$",views.excelwork),
    url(r"^postplan/$",views.postplan),
    url(r"^postevent/$",views.postevent),
    url(r"^postwork/$",views.postwork),
    url(r"^showplaninfo/$",views.showplaninfo),
    url(r"^showeventinfo/$",views.showeventinfo),
    url(r"^showworkinfo/$",views.showworkinfo),

    url(r"^exportfaeplanquestion/$",views.export_excelplan_question),
    url(r"^exportfaeeventquestion/$",views.export_excelevent_question),
    url(r"^exportfaeworkquestion/$",views.export_excelwork_question),

    url(r"^exportfaeplancomment/$",views.export_excelplan_comment),
    url(r"^exportfaeeventcomment/$",views.export_excelevent_comment),
    url(r"^exportfaeworkcomment/$",views.export_excelwork_comment),

    url(r"^exportfaelast/$",views.export_excelall),
    url(r"^exportfaethis/$",views.export_excelall_),
    url(r"^exportexcellastmonth/$",views.export_excellastmonth),
    url(r"^exportexcelthismonth/$",views.export_excelthismonth),
    url(r"^addcomment_plan/$",views.addcomment_plan),
    url(r"^addcomment_event/$",views.addcomment_event),
    url(r"^addcomment_work/$",views.addcomment_work),
    url(r"^deleteplancomment/$",views.deleteplancomment),
    url(r"^deleteeventcomment/$",views.deleteeventcomment),
    url(r"^deleteworkcomment/$",views.deleteworkcomment),

    url(r"^exportplanweekquestion/$",views.export_planweekquestion),
    url(r"^exporteventweekquestion/$",views.export_eventweekquestion),
    url(r"^exportworkweekquestion/$",views.export_workweekquestion),
    url(r"^exportplanmonthquestion/$",views.export_planmonthquestion),
    url(r"^exporteventmonthquestion/$",views.export_eventmonthquestion),
    url(r"^exportworkmonthquestion/$",views.export_workmonthquestion),
    url(r"^exportplanmonthsquestion/$",views.export_planmonthsquestion),
    url(r"^exporteventmonthsquestion/$",views.export_eventmonthsquestion),
    url(r"^exportworkmonthsquestion/$",views.export_workmonthsquestion),
    url(r"^exportplancomment/$",views.export_plancomment),
    url(r"^exporteventcomment/$",views.export_eventcomment),
    url(r"^exportworkcomment/$",views.export_workcomment),
    url(r"^exportplan/$",views.export_plan),
    url(r"^exportevent/$",views.export_event),
    url(r"^exportwork/$",views.export_work)
    
    # url(r"^list/$", List_.as_view(),name='list'),
    # url(r"^test/$", Test.as_view(),name='test')

]