from django.conf.urls import url
from forminfo import views

urlpatterns = [
    url(r"^addform-plan/$", views.addinfo_plan),
    url(r"^addinfoplan/$", views.addinfoplan_),
    url(r"^addform-event/$", views.addinfo_event),
    url(r"^addinfoevent/$", views.addinfoevent_),
    url(r"^eventrevise/$", views.revise_event),
    url(r"^planrevise/$", views.revise_plan),
    url(r"^changeplaninfo/$",views.show_plandetail),
    url(r"^changeeventinfo/$",views.show_eventdetail),
    url(r"^planresult/$",views.update_planform),
    url(r"^eventresult/$",views.update_eventform),
    url(r"^plan/$",views.info_plan),
    url(r"^event/$",views.info_event),
    url(r"^work/$",views.info_work),
    url(r"^addinfowork/$",views.addinfowork_),
    url(r"^workrevise/$", views.revise_work),
    url(r"^changeworkinfo/$",views.show_workdetail),
    url(r"^workresult/$",views.update_workform),
    url(r"^addform-work", views.addinfo_work),
    url(r"^amend-plan/$",views.amend_plan),
    url(r"^amend-event/$",views.amend_event),
    url(r"^amend-work/$",views.amend_work),
    url(r"^amendplaninfo/$",views.amendplaninfo_),
    url(r"^amendplaninfoshow/$",views.amendplaninfoshow_),
    url(r"^amendeventinfo/$",views.amendeventinfo_),
    url(r"^amendeventinfoshow/$",views.amendeventinfoshow_),
    url(r"^amendworkinfo/$",views.amendworkinfo_),
    url(r"^amendworkinfoshow/$",views.amendworkinfoshow_),
    url(r"^exportfaeplan/$",views.export_excelplan),
    url(r"^exportfaeevent/$",views.export_excelevent),
    url(r"^exportfaework/$",views.export_excelwork),
    url(r"^excelplan/$",views.excelplan),
    url(r"^excelevent/$",views.excelevent),
    url(r"^excelwork/$",views.excelwork),
    url(r"^postplan/$",views.postplan),
    url(r"^postevent/$",views.postevent),
    url(r"^postwork/$",views.postwork),
    url(r"^showplaninfo/$",views.showplaninfo),
    url(r"^showeventinfo/$",views.showeventinfo),
    url(r"^showworkinfo/$",views.showworkinfo),
    url(r"^exportfaeplanquestion/$",views.export_excelplan_question),
    url(r"^exportfaeeventquestion/$",views.export_excelevent_question),
    url(r"^exportfaeworkquestion/$",views.export_excelwork_question),
    url(r"^exportfaelast/$",views.export_excelall),
    url(r"^exportfaethis/$",views.export_excelall_)

]