# Generated by Django 2.0.8 on 2018-11-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinfo', '0005_auto_20181108_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='uptime',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='更新时间'),
        ),
    ]
