# Generated by Django 2.0.8 on 2018-12-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20181016_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='employeeid',
            field=models.CharField(max_length=10, null=True, verbose_name='工号'),
        ),
    ]
