# Generated by Django 2.0.8 on 2019-03-28 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_auto_20181226_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='updated_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='最后登录时间'),
        ),
    ]
