# Generated by Django 2.0.8 on 2018-11-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinfo', '0003_pipeline_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipeline',
            name='competitoradvantage',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='竞品优势'),
        ),
    ]
