# Generated by Django 2.0.8 on 2018-11-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellinfo', '0004_auto_20181108_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipeline',
            name='uptime',
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='filltime',
            field=models.DateField(blank=True, null=True, verbose_name='更新时间'),
        ),
    ]
