# Generated by Django 2.0.8 on 2018-11-13 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellinfo', '0007_remove_pipeline_uptime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellinfoweekly',
            name='sellname',
            field=models.CharField(max_length=10, verbose_name='填表人'),
        ),
        migrations.AlterField(
            model_name='sellinfoweekly',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo', verbose_name='填写人'),
        ),
    ]
