# Generated by Django 2.0.8 on 2018-10-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forminfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminfoevent',
            name='sellname',
            field=models.CharField(max_length=10, verbose_name='销售员姓名'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='sellname',
            field=models.CharField(max_length=10, verbose_name='销售员姓名'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='sellname',
            field=models.CharField(max_length=10, verbose_name='需求者姓名'),
        ),
    ]
