# Generated by Django 2.0.8 on 2018-10-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forminfo', '0002_auto_20181016_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminfoevent',
            name='estimate',
            field=models.IntegerField(verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfoevent',
            name='estimated_time',
            field=models.IntegerField(verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfoevent',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='满意度评分'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='estimate',
            field=models.IntegerField(verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='estimated_time',
            field=models.IntegerField(verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='满意度评分'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='estimate',
            field=models.IntegerField(verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='estimated_time',
            field=models.IntegerField(verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='满意度评分'),
        ),
    ]
