# Generated by Django 2.0.8 on 2018-10-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forminfo', '0003_auto_20181022_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminfoevent',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, default=5, null=None, verbose_name='满意度评分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, default=1, null=None, verbose_name='满意度评分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='satisfaction_score',
            field=models.IntegerField(blank=True, default=1, null=None, verbose_name='满意度评分'),
            preserve_default=False,
        ),
    ]
