# Generated by Django 2.0.8 on 2018-10-22 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forminfo', '0006_auto_20181022_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminfoevent',
            name='estimate',
            field=models.CharField(max_length=10, verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfoevent',
            name='estimated_time',
            field=models.CharField(max_length=10, verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfoevent',
            name='satisfaction',
            field=models.CharField(blank=True, default=1, max_length=10, null=None, verbose_name='评价'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='estimate',
            field=models.CharField(max_length=10, verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='estimated_time',
            field=models.CharField(max_length=10, verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfoplan',
            name='satisfaction_score',
            field=models.CharField(blank=True, default=1, max_length=10, null=None, verbose_name='满意度评分'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='estimate',
            field=models.CharField(max_length=10, verbose_name='用时估算'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='estimated_time',
            field=models.CharField(max_length=10, verbose_name='预计用时'),
        ),
        migrations.AlterField(
            model_name='forminfowork',
            name='satisfaction_score',
            field=models.CharField(blank=True, default=1, max_length=10, null=None, verbose_name='满意度评分'),
            preserve_default=False,
        ),
    ]
