# Generated by Django 2.0.8 on 2018-11-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceinfo', '0002_auto_20181119_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='assistant1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='同伙人1'),
        ),
        migrations.AddField(
            model_name='service',
            name='assistant2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='同伙人2'),
        ),
        migrations.AddField(
            model_name='service',
            name='assistant3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='同伙人3'),
        ),
        migrations.AddField(
            model_name='service',
            name='assistant4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='同伙人4'),
        ),
    ]
