# Generated by Django 2.0.8 on 2018-11-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceinfo', '0003_auto_20181124_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='assistant1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='合作人1'),
        ),
        migrations.AlterField(
            model_name='service',
            name='assistant2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='合作人2'),
        ),
        migrations.AlterField(
            model_name='service',
            name='assistant3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='合作人3'),
        ),
        migrations.AlterField(
            model_name='service',
            name='assistant4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='合作人4'),
        ),
        migrations.AlterField(
            model_name='service',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='客户电话'),
        ),
    ]
